### PR TITLE
Added "Again" button

### LINKED ISSUE #194: Add API call to regenerated requested extracts
Scenario: Someone wants Fremont data, but they want to be able to update it without having to go through the request flow again. Should we allow an "update" button, such as on /odes/extracts?

@migurski @sleepylemur would love input on this

### PR DESCRIPTION
**Pull request by migurski**
* [x] Add a re-do button.
* [x] Make the words right.

Closes #194. Looks like:

screen shot 2016-08-03 at 4 56 11 pm

### CODE REVIEW

**Comment by binx** [comment]
lol

**Comment by migurski** [comment]
Now looks like:

screen shot 2016-08-04 at 12 59 01 pm

**Comment by binx** [comment]
@souperneon thoughts?

**Comment by souperneon** [comment]
@migurski can you do that sign in magic again so i can see this page :)
🎶 Heroku don't let me sign in 🎶

**Comment by migurski** [comment]
Try now, @souperneon? https://mapzen-odes-extracts-pr-225.herokuapp.com/odes/extracts

**Comment by souperneon** [comment]
How about –
screen shot 2016-08-08 at 2 25 55 pm

Questions –
- When does the 'Update' option appear? Should we add some amount of time before you can regenerate the same extract? This can be based on a frequency we think is reasonable for updates to OSM data.
- Does the table view nest the same extract by date or is it a new row?
- Should we allow users to get updated extracts from the table view?

**Comment by binx** [comment]
Deferring 1) to @migurski, personally I think it's fine to leave it available as an option whenever.

2) I think it would replace the old extract, keeping it as the same row.
3) I would love to add this feature in the table view.

@souperneon I'm ok with the content that you proposed above, but could you please go over this again with some thought about hierarchy and consistency of style? It doesn't follow the same bold/un-bold conventions as above in the page, and I would like to avoid 5 different text treatments in one section.

**Comment by migurski** [comment]
It should always be there; otherwise we'll have to explain when it's not.

**Comment by souperneon** [comment]
1) Great. Available as soon as the extract gets created and the download links are ready. 👍 
2) This can be confusing. @binx are you imagining it moving to the top item in the table when that happens? Is it bad to just add it as a brand new extract as a new line in the table? I can imagine people doing analysis on changed data as a use case. But could go either way, as long as the recentest extract is on top of the table.
3) I'll make an issue for that. It will require some front-end magic :)

For the styling, everything is in line with the rest of the page (except the created date which can be the same as the rest of the text). I used the italics as the 'note' style that we are using in other places in the experience.
Will it be simpler to put the whole thing in a blue box? I'm not sure how much attention we want to draw to it.

**Comment by souperneon** [comment]
@binx i see the old copy on the live site.

If we can just change the second line (after the date) to read:
Need an updated version of this extract with the latest OpenStreetMap data and the same boundaries?
GET _ EXTRACT

Should I make a new issue with this?

**Pull request merged**
