### PR TITLE
Add metro and extract download sizes

### LINKED ISSUE #184: Add download size information to the metro and extract pages

### PR DESCRIPTION
**Pull request by migurski**
Added download sizes to regular and custom extract pages. Closes #184.

On custom extract pages:

screen shot 2016-08-01 at 8 09 19 pm

On regular extract pages:

screen shot 2016-08-01 at 8 09 30 pm

### CODE REVIEW

**Comment by souperneon** [comment]
@migurski 👏 
@binx for styling, what we had in the old one was pretty solid. What do you think?

screen shot 2016-08-02 at 10 09 14 am

**Comment by migurski** [comment]
I was never a fan of the old one, tbh. The buttons are too tightly-squashed.

**Comment by souperneon** [comment]
@migurski totally! Sorry should have been more clear. I mean the the typographic hierarchy

**Comment by binx** [comment]
screen shot 2016-08-02 at 10 35 42 am

**Pull request merged**
