### PR TITLE
implementing hanbyuls fallbacktile

### LINKED ISSUE #181: Properly add fallback tiles

### PR DESCRIPTION
**Pull request by binx**
closes #181

### CODE REVIEW

**Comment by migurski** [comment]
What's the best way to test this?

**Comment by binx** [comment]
erg, this is not working

@hanbyul-here I tried this in IE11 (browserstack) and got the below image, did I mess up the syntax?
screen shot 2016-07-20 at 3 49 42 pm

**Comment by hanbyul-here** [comment]
were you trying to see fallback works? [IE 11 supports WebGL](http://caniuse.com/#feat=webgl), so fallback shouldn't work. 
Based on attribution (worked) , I wonder tiles were being just slowly loaded? If you can check developer's console, it will help me figure out a lot.

**Comment by binx** [comment]
@hanbyul-here aha! ok it was just slow to load, I went back and tiles did come in.

re: tilefallback, I do see it working in an iphone5. One thing, the default attribution is still being added on the fallback tiles. Do you think we should fix this in mapzen.js, or do some sort of webGL check on our end to remove the default attribution?

screen shot 2016-07-21 at 9 27 48 am

**Comment by hanbyul-here** [comment]
Did you try `attributionText` api? 
 https://github.com/mapzen/mapzen.js#api

**Pull request merged**
