### PR TITLE
Docs addition

### PR DESCRIPTION
**Pull request by kkowalsky**
Updated the docs to reflect the new metro extracts revision

### CODE REVIEW

**Comment by migurski** [comment]
This is the most up-to-date view of this, yes? https://precog.mapzen.com/mapzen/mapzen-docs-generator/kkowalsky/new-extracts-docs/documentation/metro-extracts/

**Comment by kkowalsky** [comment]
it's just missing the capital 'T' in tutorial on tutorial.md, but otherwise yes

**Comment by rmglennon** [comment]
This is looking good.

- Love the file formats diagram, and looks like you got the headings to work.
- A lot of the images are broken links right now
- Let's crop off the extra UI from some of the images, which makes it harder to maintain and the image quite tall. For example, this once in Custom extracts works well to show only the table.
image
- Consider dumping or combining the remnants of the Overview topic. It's not really an overview now that all the content was moved elsewhere.
- I have some style comments that we can talk about or I can do. For example, use "Sentence case" in the top-level entries and any headings (such as File formats, rather than File Formats)
- Be sure to include a blank line between text and a subsequent unordered bullet list. Our markdown renderer requires that (but GitHub does not), and it trips everyone up in docs and on the blog. Like in this section documentation/metro-extracts/fileformat/#data-split-by-osm-tags

**Comment by kkowalsky** [comment]
-fixed the image links
-clipped images as much as possible
-we had enough head nods to delete the overview section (I updated the config file as well in docs-generator)
-fixed most style considerations, please double check this next commit
-fixed bullet list

**Pull request merged**
