### PR TITLE
Added user information to determine if they are logged in

### LINKED ISSUE #114: Surface login_status on templates, so we can show the requested extracts page

### PR DESCRIPTION
**Pull request by migurski**
On ODES pages, `user_id` and `user_nickname` template variables determine whether a user is authenticated. @binx handing this over to you for UI.

* [x] Showed logout button on ODES pages with user's nickname
* [x] Make the logout form look like it belongs with the styleguide.
* [x] Link to existing extracts page on the index if user is logged in

Closes #114.

### CODE REVIEW

**Comment by binx** [comment]
screen shot 2016-07-12 at 10 31 52 am

**Comment by binx** [comment]
@migurski can we add login information on the index page too?

**Comment by migurski** [comment]
Back to you; give it a try via https://mapzen-odes-extracts-pr-122.herokuapp.com/oauth/hello

**Comment by binx** [comment]
@migurski what do you think of this?
screen shot 2016-07-12 at 4 23 24 pm

**Comment by migurski** [comment]
LGTM.

**Pull request merged**
