### PR TITLE
Added cities-extractor.json response

### LINKED ISSUE #124: Provide ops with a place to download cities.json
Should match https://github.com/mapzen/metroextractor-cities/blob/master/cities.json in layout, and be useable by @heffergm in `metroextractor-cities` code.

### PR DESCRIPTION
**Pull request by migurski**
@heffergm does this syntax match what you need? https://mapzen-odes-extracts-pr-125.herokuapp.com/cities-extractor.json (give it a minute to deploy)

Closes #124.

### CODE REVIEW

**Comment by heffergm** [comment]
I've already made all my changes to suite the json you pointed me at earlier, it's completely fine like this: https://github.com/mapzen/data-pages/blob/odes-client/cities.json

**Comment by migurski** [comment]
Okay, but can you pull it from a mapzen.com instead of a Github one?

**Comment by migurski** [comment]
(I don't want to have an invisible dependency on the cities.json format lying around; would prefer to have it be a tested code path)

**Comment by heffergm** [comment]
I can get it from wherever you put it.

Il Ven 8 Lug 2016, 5:37 PM migurski <notifications@github.com> ha scritto:

> Okay, but can you pull it from a mapzen.com instead of a Github one?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mapzen/data-pages/pull/125#issuecomment-231479046>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAmb4RIfeXFXp28Ge-t26QdzgSsOTFGPks5qTsMagaJpZM4JIar9>
> .
>
-- 

- Grant

**Comment by migurski** [comment]
Cool, how about this? https://mapzen-odes-extracts-pr-125.herokuapp.com/cities-extractor.json

Temporary URL for testing time will be at https://mapzen.com/data/metro-extracts-alt/cities-extractor.json, later it’s likely to be at https://mapzen.com/data/metro-extracts/cities-extractor.json.

**Comment by migurski** [comment]
If you’re good with this, feel free to merge. I’ve added tests and I’m done with the code.

**Pull request merged**
