### PR TITLE
first pass at ways to request an extract

### LINKED ISSUE #34: Explore options for making a request

### PR DESCRIPTION
**Pull request by binx**
closes #34

### CODE REVIEW

**Comment by migurski** [comment]
Looking at https://mapzen-odes-extracts-pr-35.herokuapp.com/static/index.html, I like this direction. Couple thoughts as I interact with it:

* When typing, we get auto-complete for existing extracts. Could we use autocomplete with Mapzen Search instead, to make it possible to show existing extracts based on coverage rather than name matches? E.g. “Fremont” could get me to the overlapping SF Bay Area extract as part of the autocomplete process.
* The visible results work well as boxes. They might also need to show up as text or a list to the right of the map? For a really big overlapping request, the whole map is blood-red due to a big bbox, which is odd.

**Comment by binx** [comment]
@migurski since this PR was supposed to be about ways to make a request, I'd like to move the "contained in an overlapping area" to another issue

**Comment by migurski** [comment]
Okay!

The right-hand side is still a bit weird; do you want to leave that for another issue?

**Comment by binx** [comment]
Open the page and see this
screen shot 2016-06-21 at 3 35 06 pm

Start typing, filter the list below and also see autocomplete suggestions
screen shot 2016-06-21 at 3 35 19 pm

type out a thing and hit enter if the extract exists
image

selecting an extract from the drop-down menu that already exists: not great! addressed by #37 
image

if it does not you get this
image

**Pull request merged**
