### PR TITLE
moving email CSS styles to inline

### LINKED ISSUE #128: Switch email CSS to inline

### PR DESCRIPTION
**Pull request by binx**
closes #128

### CODE REVIEW

**Comment by binx** [comment]
I'm not sure if we can really test this until it's merged in... hopefully this fixes our style woes?

**Comment by migurski** [comment]
Eh, let’s find out.

**Comment by migurski** [comment]
…actually, we _can_ test it. I’m going to add an OAuth info to this PR app so you can test.

**Comment by binx** [comment]
screen shot 2016-07-12 at 3 05 02 pm

yasssss

**Comment by migurski** [comment]
Still need to have this branch be testable with real extracts by email?

**Comment by binx** [comment]
@migurski I think we're good, I got that email delivered to me so I think it's good to merge in

**Comment by migurski** [comment]
K, just waiting for a test email to me as well and then I’ll merge.

How did you get that email delivered from the code on this branch?

**Comment by binx** [comment]
I'm honestly not sure? I submitted an extract request on my local build and it sent me an email with updated CSS

**Comment by migurski** [comment]
Oh, local, of course.

**Pull request merged**
