### PR TITLE
Connect to Mapzen with OAuth

### LINKED ISSUE #46: Authenticate with Mapzen via OAuth
Use https://github.com/mapzen/wiki/wiki/mapzen.com-OAuth to connect.

### PR DESCRIPTION
**Pull request by migurski**
Test authentication here: https://mapzen-odes-extracts-pr-52.herokuapp.com/oauth/hello

Closes #46.

It will ask you to authenticate with Mapzen, and then (after you’re successful) will return you to a page where it knows your name and you can log back out.

This just verifies that the OAuth loop is working. Assigning to @sleepylemur to check my use of Mapzen OAuth loop. I’d also like to borrow [Github’s `state` feature](https://developer.github.com/v3/oauth/#parameters):

> An unguessable random string. It is used to protect against cross-site request forgery attacks.

### CODE REVIEW

**Comment by sleepylemur** [comment]
@migurski looks fine to me.

you can pass in a state parameter in the authorization step and it'll get passed back to your redirect. not sure if you wanted to do that instead of keeping it in a cookie. i added the state parameter to the [oauth wiki](https://github.com/mapzen/wiki/wiki/mapzen.com-OAuth#1-redirect-users-to-request-mapzen-access) for clarity.

the 'tell mapzen its ok' form seems confusing to me because that suggests that they are going to a 3rd party site, but in this case they are going from mapzen to mapzen. it should work fine, just seems odd from a ux/branding perspective.

and then a minor quibble: it seems odd to name the result of the [current_developer query](https://github.com/mapzen/data-pages/blob/9af9909c628eb53bebbdb62bd80dc19fd9836e33/App/oauth.py#L173) `_`.

**Comment by migurski** [comment]
Thanks @sleepylemur, glad to see that `state` works!

**Comment by migurski** [comment]
I’ve added `state` and renamed the `_` variable. The form and button present here will not be used in the completed application; it’s enough demo to show that authentication can work. We’re likely to use a flow that requires authentication only at the last step of the process, as part of a submit flow.

**Comment by sleepylemur** [comment]
looks good to me

**Comment by migurski** [comment]
Thanks!

**Pull request merged**
