### PR TITLE
switching to new links

### LINKED ISSUE #242: Update links to documentation throughout new extracts site
We made some changes to the documentation file names and need to update the links. There are redirects in place, but let's send people straight there. The main documentation link stays the same.

Tutorial
OLD: https://mapzen.com/documentation/metro-extracts/walkthrough/
NEW: https://mapzen.com/documentation/metro-extracts/tutorial/

File Format Guide
OLD: https://mapzen.com/documentation/metro-extracts/overview/#choose-a-file-format/
NEW: https://mapzen.com/documentation/metro-extracts/file-format/

This also applies to anywhere else these links are used, such as "If you're unsure of which file to pick, check out our format guide."

### PR DESCRIPTION
**Pull request by binx**
closes #242

### CODE REVIEW

**Comment by souperneon** [comment]
@binx Just noticed that Rhonda missed mentioning some other links:
**OSM2PGSQL**
New link: https://mapzen.com/documentation/metro-extracts/file-format/#data-split-by-geometry

**IMPOSM**
New link: https://mapzen.com/documentation/metro-extracts/file-format/#data-split-by-osm-tags

**PBF & XML**
New link: https://mapzen.com/documentation/metro-extracts/file-format/#raw-osm-data

**Coastlines**
New link: https://mapzen.com/documentation/metro-extracts/file-format/#coastlines

**Comment by binx** [comment]
@souperneon thanks for the heads up!

I'm confused about this line though, could you elaborate? "Tutorial, File format guide have redirects on this page but not on the landing page for Metro Extracts"

**Comment by binx** [comment]
Also, how do we want to style the coastlines link?
screen shot 2016-08-08 at 12 01 01 pm

**Comment by souperneon** [comment]
Sure… I thought for a minute it would be confusing when I was writing it ;)

On https://mapzen.com/data/metro-extracts/ the 'Tutorial' link goes straight to https://mapzen.com/documentation/metro-extracts/tutorial/
But on https://mapzen.com/data/metro-extracts/metro/dubai_abu-dhabi/ (for example) the 'Tutorial' has the link https://mapzen.com/documentation/metro-extracts/walkthrough/ that redirects to https://mapzen.com/documentation/metro-extracts/tutorial/

For Coastlines, we can change the words to
Coastlines (Shapefiles)
WATER | LAND
and add the link to 'Shapefiles'. What do you think? I think it's more consistent as Shapefile is kind of the format here/

**Pull request merged**
